### ISSUE TITLE
installing pandas while using CRC machine

### ISSUE THREAD

**Issue by mclay1** [crcresearch/GOS#20]
I am working on going through the steps in the GOS read me while using the CRC machine and am coming across errors while executing migration.py and VizDemo.py because pandas will not properly install. I use the command pip3 install numpy pandas and an error message came up saying permission denied: '/opt/crc/p/python/3.6.0/gcc/6.2.0/lib/python3.6/site-packages/pandas'

**Comment by johare2** [comment]
I had the same issue. 
I think its these commands to install pandas locally instead:

module load python3
pip3 install --user pandas
